/**
 * 菜单图标：将菜单管理中配置的图标名称映射为 Element Plus 图标组件
 * 后端菜单 icon 字段存的是名称字符串（如 home / user），这里统一映射
 */
import type { Component } from 'vue'
import {
  HomeFilled,
  User,
  UserFilled,
  Setting,
  Menu as MenuIcon,
  Odometer,
  Grid,
  DataLine,
  Files,
  Document,
  Folder,
  List,
  Tools,
  Lock,
  Tickets,
  Calendar,
  Bell,
  ChatDotRound,
  Star,
  Search,
  Edit,
  Delete,
  Plus,
  Share,
  Refresh,
  Filter,
  Link,
  CopyDocument,
  QuestionFilled,
  InfoFilled,
  WarningFilled,
  CircleCheck,
  CircleClose,
  UploadFilled,
  Picture,
  Histogram,
  PieChart,
  TrendCharts,
  Monitor,
  Cpu,
  Connection,
  Key,
  Medal,
  Trophy,
  Box,
  ShoppingCart,
  Money,
  Position,
  Location,
  Phone,
  Message,
  Reading,
  Notebook,
  Collection,
} from '@element-plus/icons-vue'

const iconMap: Record<string, Component> = {
  home: HomeFilled,
  user: User,
  setting: Setting,
  settings: Setting,
  menu: MenuIcon,
  dashboard: Odometer,
  odometer: Odometer,
  app: Grid,
  apps: Grid,
  grid: Grid,
  list: List,
  files: Files,
  file: Document,
  document: Document,
  folder: Folder,
  data: DataLine,
  chart: DataLine,
  lineChart: TrendCharts,
  pieChart: PieChart,
  histogram: Histogram,
  tools: Tools,
  lock: Lock,
  tickets: Tickets,
  calendar: Calendar,
  bell: Bell,
  message: ChatDotRound,
  chat: ChatDotRound,
  star: Star,
  search: Search,
  edit: Edit,
  delete: Delete,
  plus: Plus,
  share: Share,
  refresh: Refresh,
  filter: Filter,
  link: Link,
  copy: CopyDocument,
  question: QuestionFilled,
  info: InfoFilled,
  warning: WarningFilled,
  check: CircleCheck,
  close: CircleClose,
  upload: UploadFilled,
  picture: Picture,
  image: Picture,
  monitor: Monitor,
  cpu: Cpu,
  connection: Connection,
  key: Key,
  medal: Medal,
  trophy: Trophy,
  box: Box,
  cart: ShoppingCart,
  money: Money,
  position: Position,
  location: Location,
  phone: Phone,
  reading: Reading,
  notebook: Notebook,
  collection: Collection,
}

/** 图标选择器使用的图标列表 */
export const iconList: { name: string; icon: Component }[] = Object.entries(iconMap).map(([name, icon]) => ({
  name,
  icon,
}))

/** 根据图标名称解析图标组件，未配置时使用默认图标 */
export function resolveMenuIcon(name?: string): Component {
  if (name && iconMap[name]) return iconMap[name]
  return MenuIcon
}

export { UserFilled }
